[web]
web-a.ru-central1.internal
web-b.ru-central1.internal

[zabbix]
zabbix.ru-central1.internal

[bastion]
bastion.ru-central1.internal ansible_connection=local

[logging]
elasticsearch.ru-central1.internal
kibana.ru-central1.internal
